i_str_l =     [
        "import tkinter                        ",
        "import ntpath                         ",
        "from pynput.keyboard import Controller",
        "import simplejson                     ",
        "from operator import methodcaller     ",
        "import tkinter.ttk                    ",
        "from pynput.keyboard import Listener  ",
        "import _tkinter                       ",
        "from datetime import datetime         ",
        "from subprocess import PIPE           ",
        "from tkinter import filedialog        ",
        "import uuid                           ",
        "import ctypes                         ",
        "import json                           ",
        "import pyperclip                      ",
        "from dateutil.parser import parse     ",
        "import unittest                       ",
        "from tkinter import *                 ",
        "from setuptools import setup          ",
        "import six                            ",
        "import shutil                         ",
        "from os import listdir                ",
        "import traceback                      ",
        "import glob                           ",
        "import sys                            ",
        "from fractions import Fraction        ",
        "import subprocess                     ",
        "from tkinter.ttk import *             ",
        "from ctypes import windll             ",
        "from pynput.keyboard import Key       ",
        "import keyboard                       ",
        "import stat                           ",
        "from functools import wraps           ",
        "import time                           ",
        "import math                           ",
        "from pynput import keyboard           ",
        "import csv                            ",
        "import threading                      ",
        "from func_timeout import func_timeout ",
        "from decimal import Decimal           ",
        "import argparse                       ",
        "from operator import attrgetter       ",
        "import os                             ",
        "from collections import namedtuple    ",
        "import textwrap                       ",
        "import string                         ",
        "import datetime                       ",
        "import tkinter.filedialog             ",
        "import pygame                         ",

    ]


if __name__ == '__main__':
    import import_size
    import_size.main()
